name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'

      - name: Start FTP test server
        run: docker compose up -d

      - name: Show running containers
        run: docker compose ps

      - name: Wait for FTP server to be ready
        run: |
          timeout=30
          counter=0
          until docker exec embulk-input-ftp_server nc -z localhost 21 2>/dev/null || [ $counter -eq $timeout ]; do
            echo "Waiting for FTP server to be ready... ($counter/$timeout)"
            counter=$((counter+1))
            sleep 1
          done

          if [ $counter -eq $timeout ]; then
            echo "FTP server did not start in time!"
            docker compose logs
            exit 1
          fi

          echo "FTP server is ready!"

      - name: Check
        run: ./gradlew check --stacktrace --info
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests
          path: ./build/reports/tests/test

